ENV_TEMPLATE = """# Ragdoll local backend configuration.
# This file belongs to Ragdoll, not to an application workspace.
RAGDOLL_PROVIDER=auto
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
GEMINI_API_KEY=
OPENAI_MODEL=gpt-4o
ANTHROPIC_MODEL=claude-3-5-sonnet-20241022
GEMINI_MODEL=gemini-1.5-flash

# Local API is intentionally loopback-only in Core.
RAGDOLL_HOST=127.0.0.1
RAGDOLL_PORT=8765
RAGDOLL_ALLOW_REMOTE_BIND=false

RAGDOLL_HISTORY_TOKEN_BUDGET=1500
RAGDOLL_PROJECT_CONTEXT_TOKEN_BUDGET=2200
RAGDOLL_MAX_OUTPUT_TOKENS=4096

# Security / resource limits.
RAGDOLL_OUTBOUND_SECRET_POLICY=redact
RAGDOLL_TELEMETRY=false
RAGDOLL_CLOUD_SYNC=false
RAGDOLL_MAX_REQUEST_BYTES=2097152
RAGDOLL_MAX_PROVIDER_RESPONSE_BYTES=8388608
RAGDOLL_PROVIDER_TIMEOUT_SECONDS=90
RAGDOLL_LOG_LEVEL=INFO
"""
